### PR TITLE
Support for explicitly setting the download URL

### PR DESCRIPTION
**Pull request by vjrantal**

### CODE REVIEW

**Comment by vjrantal** [comment]
@ktrzeciaknubisa: It would be nice if this would get integrated and a new npm released published since then we could use the npm release of jxc to install jxcore-cordova from a custom location.

**Comment by ktrzeciaknubisa** [comment]
Thanks @vjrantal !

**Comment by ktrzeciaknubisa** [comment]
Its published now on npm repo too :)

**Comment by vjrantal** [comment]
@ktrzeciaknubisa: Fantastic! Thanks a lot for the quick actions! :+1:

**Pull request merged**
